-- =====================================================================
-- ROBLE STUDIO - CONFIGURACIÓN DE BASE DE DATOS (SUPABASE SQL)
-- =====================================================================
--
-- Instrucciones de uso:
-- 1. Ve al panel de control de tu proyecto en Supabase (https://supabase.com).
-- 2. Entra en la sección "SQL Editor" en el menú de la izquierda.
-- 3. Haz clic en "New Query" (Nueva Consulta).
-- 4. Pega todo el contenido de este archivo en el editor de SQL.
-- 5. Haz clic en el botón "Run" (Ejecutar) en la esquina inferior derecha.
--
-- Esto creará automáticamente las tablas necesarias para guardar las
-- cotizaciones del chatbot e informes de agendamiento.
-- =====================================================================

-- 1. Tabla de Cotizaciones y Contactos (Leads)
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    source TEXT DEFAULT 'Roble Assistant Chatbot' NOT NULL,
    client_name TEXT NOT NULL,
    client_business TEXT,
    client_sector TEXT,
    client_email TEXT NOT NULL,
    client_phone TEXT,
    client_goal TEXT
);

-- Habilitar comentarios en la tabla
COMMENT ON TABLE public.leads IS 'Almacena la información de los leads capturados por el asistente virtual de Roble Studio.';

-- 2. Tabla de Calendario y Agendamientos (Bookings)
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    business TEXT,
    website TEXT,
    goal TEXT,
    date_key TEXT NOT NULL,          -- Formato YYYY-MM-DD
    booking_time TEXT NOT NULL,      -- Formato HH:MM
    timezone TEXT DEFAULT 'America/Mexico_City' NOT NULL,
    timezone_label TEXT DEFAULT 'CDMX' NOT NULL
);

-- Habilitar comentarios en la tabla
COMMENT ON TABLE public.bookings IS 'Almacena las citas de videollamadas estratégicas confirmadas en el programador de Roble Studio.';

-- 3. Crear políticas seguras o RLS (Opcional)
-- Nota: Dado que nuestro backend de Node.js interactuará con Supabase del lado
-- del servidor utilizando la API Key (Service Role), las políticas de RLS
-- se omitirán o se pueden desactivar para estas tablas. Sin embargo, si deseas
-- habilitar RLS, ejecuta las siguientes líneas para permitir escrituras anónimas
-- (o solo lecturas seguras):

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Política para permitir que cualquiera pueda insertar datos (escritura pública móvil)
CREATE POLICY "Permitir inserciones públicas en leads" 
    ON public.leads FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Permitir inserciones públicas en bookings" 
    ON public.bookings FOR INSERT 
    WITH CHECK (true);

-- Política para que solo usuarios autenticados (o el backend vía Service Key) puedan leer datos
CREATE POLICY "Restringir lecturas a Service Key o Autenticados"
    ON public.leads FOR SELECT
    USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Restringir lecturas de bookings"
    ON public.bookings FOR SELECT
    USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
